// 22. 10.11.2022 - Формы/2. Home work/HomeWork/components/task01/Task01.jsx
﻿// компонент "Задание 1"
class Task01 extends React.Component {
    render() {
        return (
            <section className="mx-5 my-4 bg-light shadow-sm border rounded-3 min-vh-100 p-3">
                <h4 className="text-center">Задание 1</h4>
                <div className="row">
                    <Component01/>
                    <Component02/>
                    <Component03/>
                    <Component04/>
                </div>
            </section>
        );
    }
}

// 18. 26.10.2022 - Routing/2. Home work/Горячев Михаил/src/app/task01/task01.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-task01',
    templateUrl: './task01.component.html'
})
export class Task01Component implements OnInit {

    ngOnInit() {
    }
}

<section class="mx-5 my-4 bg-light shadow-sm border rounded-3 min-vh-100 p-3">

    <h4 class="text-center">Задание 1. Книга</h4>

    <router-outlet></router-outlet>

</section>
